<?xml version="1.0" encoding="utf-8"?><Database Name="DB_WEBAPI" Class="LinQClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-RRRGOKE;Initial Catalog=DB_WEBAPI;Integrated Security=True;Encrypt=False;TrustServerCertificate=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="DB_WEBAPIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblCategories" Member="tblCategories">
    <Type Name="tblCategory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="category" Type="System.String" DbType="NChar(20)" CanBeNull="true" />
      <Association Name="tblCategory_tblProduct" Member="tblProducts" ThisKey="id" OtherKey="catID" Type="tblProduct" />
    </Type>
  </Table>
  <Table Name="dbo.tblProducts" Member="tblProducts">
    <Type Name="tblProduct">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="unitInStock" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="catID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tblCategory_tblProduct" Member="tblCategory" ThisKey="catID" OtherKey="id" Type="tblCategory" IsForeignKey="true" />
    </Type>
  </Table>
</Database>