<?xml version="1.0" encoding="utf-8"?><Database Name="j2ee" Class="myLinqClassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=demouit.database.windows.net;Initial Catalog=j2ee;Persist Security Info=True;User ID=trantu" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="j2eeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CT_DonHang" Member="CT_DonHangs">
    <Type Name="CT_DonHang">
      <Column Name="MaChiTietDDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="dongia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="soluong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaDDH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonHang_CT_DonHang" Member="DonHang" ThisKey="MaDDH" OtherKey="MaDDH" Type="DonHang" IsForeignKey="true" />
      <Association Name="SanPham_CT_DonHang" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThanhVien" Member="ThanhViens">
    <Type Name="ThanhVien">
      <Column Name="MaTV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MaQuyen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ThanhVien_KhachHang" Member="KhachHangs" ThisKey="MaTV" OtherKey="MaTV" Type="KhachHang" />
      <Association Name="Quyen_ThanhVien" Member="Quyen" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="Quyen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CT_PhieuNhap" Member="CT_PhieuNhaps">
    <Type Name="CT_PhieuNhap">
      <Column Name="MaChiTietPN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DonGiaNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuongNhap" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaPN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="PhieuNhap_CT_PhieuNhap" Member="PhieuNhap" ThisKey="MaPN" OtherKey="maPN" Type="PhieuNhap" IsForeignKey="true" />
      <Association Name="SanPham_CT_PhieuNhap" Member="SanPham" ThisKey="MaSP" OtherKey="MaSP" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DaThanhToan" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayGiao" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TinhTrangGiaoHang" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaKH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DaHuy" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DaXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="UuDai" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DonHang_CT_DonHang" Member="CT_DonHangs" ThisKey="MaDDH" OtherKey="MaDDH" Type="CT_DonHang" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="MaKH" OtherKey="MaKH" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="MaKH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="sodienthoai" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TenKH" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MaTV" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaThanhVien" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="MaKH" OtherKey="MaKH" Type="DonHang" />
      <Association Name="ThanhVien_KhachHang" Member="ThanhVien" ThisKey="MaTV" OtherKey="MaTV" Type="ThanhVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhaCungCap" Member="NhaCungCaps">
    <Type Name="NhaCungCap">
      <Column Name="MaNCC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TenNCC" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="NhaCungCap_SanPham" Member="SanPhams" ThisKey="MaNCC" OtherKey="MaNCC" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="TaiKhoan" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Ten" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhaSanXuat" Member="NhaSanXuats">
    <Type Name="NhaSanXuat">
      <Column Name="MaNSX" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Logo" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="TenNSX" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ThongTin" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="NhaSanXuat_SanPham" Member="SanPhams" ThisKey="MaNSX" OtherKey="MaNSX" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.PhieuNhap" Member="PhieuNhaps">
    <Type Name="PhieuNhap">
      <Column Name="maPN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DaXoa" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayNhap" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="PhieuNhap_CT_PhieuNhap" Member="CT_PhieuNhaps" ThisKey="maPN" OtherKey="MaPN" Type="CT_PhieuNhap" />
    </Type>
  </Table>
  <Table Name="dbo.Quyen" Member="Quyens">
    <Type Name="Quyen">
      <Column Name="MaQuyen" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQuyen" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Quyen_ThanhVien" Member="ThanhViens" ThisKey="MaQuyen" OtherKey="MaQuyen" Type="ThanhVien" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CauHinh" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hinh1" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Hinh2" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Hinh3" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Hinh4" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MaLoaiSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TenSP" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="MaNCC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaNSX" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="SanPham_CT_DonHang" Member="CT_DonHangs" ThisKey="MaSP" OtherKey="MaSP" Type="CT_DonHang" />
      <Association Name="SanPham_CT_PhieuNhap" Member="CT_PhieuNhaps" ThisKey="MaSP" OtherKey="MaSP" Type="CT_PhieuNhap" />
      <Association Name="NhaCungCap_SanPham" Member="NhaCungCap" ThisKey="MaNCC" OtherKey="MaNCC" Type="NhaCungCap" IsForeignKey="true" />
      <Association Name="NhaSanXuat_SanPham" Member="NhaSanXuat" ThisKey="MaNSX" OtherKey="MaNSX" Type="NhaSanXuat" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.sysdiagrams" Member="sysdiagrams">
    <Type Name="sysdiagram">
      <Column Name="name" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="principal_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="diagram_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="version" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="definition" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.SanPhamCustom" Member="SanPhamCustoms">
    <Type Name="SanPhamCustom">
      <Column Name="TenSP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuongTon" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>